[package]
name = "k-pass-gen"
version = "0.2.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["image"] }
fastrand = "2.3.0"

serde = { version = "1", features = ["derive"] }
toml = "0.8.22"
dirs = "6.0.0"
